[build-system]
requires = ["py-build-cmake"]
build-backend = "py_build_cmake.build"

[project]
name = "dectalk"
version = "0.0.1"

[tool.py-build-cmake.cmake]
source_path = "dectalk"
options = { "CMAKE_INSTALL_LIBDIR" = "dectalk/" }

[tool.py-build-cmake.sdist]
include = ["dectalk"]

[tool.py-build-cmake.module]
directory = "src"
# namespace=true
