name: Build Python Wheel

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build Python Wheel
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/dectalk/
    permissions:
      id-token: write
      contents: write

    strategy:
      matrix:
        platform:
          - musllinux_1_2_x86_64
          - manylinux_2_28_x86_64
        python: ["3.9", "3.10", "3.11", "3.12"]

    container:
      image: quay.io/pypa/${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheel
        run: |
          python${{ matrix.python }} -m pip wheel .

      - name: Repair wheel with auditwheel
        run: |
          auditwheel repair *.whl --wheel-dir dist

      - name: List built wheels
        run: ls -lh dist

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ matrix.platform }}
          path: ./dist/*.whl


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: "*"
          merge-multiple: true
      - run: ls -R dist

  deploy-gh:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: "*"
          merge-multiple: true
      - name: Upload wheel to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pypi:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: "*"
          merge-multiple: true
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
